services:
  postgres:
    ports: !reset []

  backend-api:
    networks:
      - default
      - kind

  worker-provisioner:
    networks:
      - default
      - kind

networks:
  kind:
    external: true
