kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30909
        hostPort: 30909
        listenAddress: "127.0.0.1"
        protocol: TCP
      - containerPort: 31879
        hostPort: 31879
        listenAddress: "127.0.0.1"
        protocol: TCP
