// @ts-nocheck
const fs = require("fs");
const path = require("path");
const { AGENT_RUNTIME_PORT, OPENCLAW_GATEWAY_PORT } = require("./contracts");
const {
  NORA_INTEGRATION_TOOL_COMMAND,
  NORA_INTEGRATIONS_SKILL_FILE,
  NORA_SYNC_INTEGRATIONS_CATALOG_FILE,
  NORA_SYNC_INTEGRATIONS_DIR,
  buildIntegrationSkillMarkdown,
  buildSplitIntegrationManifest,
} = require("./integrationTools");

const TSX_PACKAGE_SPEC = process.env.OPENCLAW_TSX_PACKAGE || "tsx@4.21.0";

function runtimeSourcePath(relPath) {
  return path.resolve(__dirname, relPath);
}

function readRuntimeSource(relPath) {
  return fs.readFileSync(runtimeSourcePath(relPath), "utf8");
}

const RUNTIME_FILES = [
  "containerCommand.ts",
  "contracts.ts",
  "runtimeBootstrap.ts",
  // Required by runtimeBootstrap's require("./mcpServersConfig") — every module
  // runtimeBootstrap imports relatively must ship into the container with it,
  // or the in-container runtime server fails at load.
  "mcpServersConfig.ts",
  "execEndpoint.ts",
  "integrationTools.ts",
  "integrationToolCli.ts",
  "server.ts",
  "agent.ts",
].map((relPath) => ({
  relPath,
  source: readRuntimeSource(relPath),
  sourceB64: Buffer.from(readRuntimeSource(relPath)).toString("base64"),
}));

const INTEGRATION_TOOL_WRAPPER_SOURCE = [
  "#!/usr/bin/env sh",
  'TSX_BIN="${OPENCLAW_TSX_BIN:-$(command -v tsx 2>/dev/null || true)}"',
  '[ -n "$TSX_BIN" ] || TSX_BIN="tsx"',
  'exec "$TSX_BIN" /opt/openclaw-runtime/lib/integrationToolCli.ts "$@"',
  "",
].join("\n");
const INTEGRATION_TOOL_WRAPPER_B64 = Buffer.from(INTEGRATION_TOOL_WRAPPER_SOURCE, "utf8").toString(
  "base64",
);

const OPENCLAW_WORKSPACE_ROOT = "/root/.openclaw/workspace";
const OPENCLAW_LEGACY_AGENT_TEMPLATE_ROOT = "/root/.openclaw/agents/main/agent";
const OPENCLAW_AUTH_PROFILES_PATH = `${OPENCLAW_LEGACY_AGENT_TEMPLATE_ROOT}/auth-profiles.json`;
const NORA_INTEGRATIONS_CONTEXT_FILE = "integrations/NORA_INTEGRATIONS.md";
const NORA_INTEGRATIONS_PROMPT_BEGIN = "<!-- NORA_INTEGRATIONS_BEGIN -->";
const NORA_INTEGRATIONS_PROMPT_END = "<!-- NORA_INTEGRATIONS_END -->";

function stripGeneratedIntegrationPromptBlock(content) {
  const raw = typeof content === "string" ? content : "";
  const pattern = new RegExp(
    `\\n?${NORA_INTEGRATIONS_PROMPT_BEGIN}[\\s\\S]*?${NORA_INTEGRATIONS_PROMPT_END}\\n?`,
    "g",
  );
  return raw
    .replace(pattern, "\n")
    .replace(/\n{3,}/g, "\n\n")
    .trimEnd();
}

function buildIntegrationPromptPointerMarkdown() {
  return [
    NORA_INTEGRATIONS_PROMPT_BEGIN,
    "",
    "## Nora Integrations",
    "",
    "- Connected integrations for this agent are generated in `integrations/`.",
    "- Check `integrations/NORA_INTEGRATIONS.md` before saying no integration is connected.",
    "- Use `nora-integration-tool --list` to list executable tools.",
    "- Use `nora-integration-tool <tool_name> '<json input>'` to invoke supported provider tools.",
    "- Never print credential values; provider detail files are private runtime config.",
    "",
    NORA_INTEGRATIONS_PROMPT_END,
  ].join("\n");
}

function upsertGeneratedIntegrationPromptBlock(content) {
  const cleaned = stripGeneratedIntegrationPromptBlock(content);
  return `${cleaned.trimEnd()}\n\n${buildIntegrationPromptPointerMarkdown()}\n`.trimStart();
}

function buildEmptyIntegrationContextMarkdown() {
  return [
    "# Nora Integrations",
    "",
    "This file is generated by Nora from the active integrations connected to this agent.",
    "Use only the providers listed here.",
    `Machine-readable integration metadata is available in \`${NORA_SYNC_INTEGRATIONS_DIR}\` on OpenClaw. Start with \`${NORA_SYNC_INTEGRATIONS_CATALOG_FILE}\`, then follow each \`detailsFile\` only when credential/tool details are needed.`,
    "When a connected tool shows runtime execution below, use the generated `nora-integrations` skill and `nora-integration-tool` command through the exec tool.",
    "",
    "No active Nora integrations are currently synced to this agent.",
    "",
  ].join("\n");
}

function buildRuntimeBootstrapFiles() {
  return RUNTIME_FILES.map(({ relPath, source }) => ({ relPath, source }));
}

function buildIntegrationToolWrapperScript() {
  return INTEGRATION_TOOL_WRAPPER_SOURCE;
}

// Allowlist: alphanumerics, dot, underscore, dash, and forward slash only.
// Blocks shell metacharacters ($, `, \, ", ', ;, newline, whitespace, etc.)
// so bootstrap paths cannot break out of their quoted context and execute
// command substitution when interpolated into `sh -c` strings.
const SAFE_TEMPLATE_PATH_RE = /^[A-Za-z0-9._/-]+$/;

function normalizeTemplateEntry(entry, baseDir) {
  if (!entry || typeof entry !== "object") return null;
  const rawPath = String(entry.path || "")
    .trim()
    .replace(/\\/g, "/");
  if (!rawPath) return null;

  const normalizedPath = path.posix.normalize(rawPath).replace(/^\/+/, "");
  if (!normalizedPath || normalizedPath === "." || normalizedPath.startsWith("../")) {
    return null;
  }
  if (!SAFE_TEMPLATE_PATH_RE.test(normalizedPath)) {
    return null;
  }

  let contentBuffer;
  if (typeof entry.contentBase64 === "string" && entry.contentBase64) {
    try {
      contentBuffer = Buffer.from(entry.contentBase64, "base64");
    } catch {
      return null;
    }
  } else if (typeof entry.content === "string") {
    contentBuffer = Buffer.from(entry.content, "utf8");
  } else {
    return null;
  }

  return {
    targetPath: path.posix.join(baseDir, normalizedPath),
    contentBuffer,
    mode: Number.isInteger(entry.mode) ? entry.mode : 0o644,
  };
}

function normalizeTemplatePayloadEntries(templatePayload = {}) {
  const files = Array.isArray(templatePayload.files) ? templatePayload.files : [];
  const memoryFiles = Array.isArray(templatePayload.memoryFiles) ? templatePayload.memoryFiles : [];

  const entries = [
    ...files
      .flatMap((entry) => [
        normalizeTemplateEntry(entry, OPENCLAW_WORKSPACE_ROOT),
        normalizeTemplateEntry(entry, OPENCLAW_LEGACY_AGENT_TEMPLATE_ROOT),
      ])
      .filter(Boolean),
    ...memoryFiles.map((entry) => normalizeTemplateEntry(entry, "/root/.openclaw")).filter(Boolean),
  ];

  return withIntegrationBootstrapEntries(entries);
}

function isGeneratedIntegrationTarget(targetPath) {
  const relativeWorkspacePath = targetPath.startsWith(`${OPENCLAW_WORKSPACE_ROOT}/`)
    ? targetPath.slice(OPENCLAW_WORKSPACE_ROOT.length + 1)
    : "";
  if (!relativeWorkspacePath) return false;
  return (
    relativeWorkspacePath === NORA_INTEGRATIONS_CONTEXT_FILE ||
    relativeWorkspacePath === NORA_INTEGRATIONS_SKILL_FILE ||
    relativeWorkspacePath === "integrations/integrations.json" ||
    relativeWorkspacePath.startsWith("integrations/integrations.")
  );
}

function isTemplateToolsPath(targetPath, rootDir) {
  return targetPath === path.posix.join(rootDir, "TOOLS.md");
}

function withIntegrationBootstrapEntries(entries = []) {
  const nextEntries = [];
  let hasWorkspaceTools = false;
  let hasLegacyTools = false;

  for (const entry of entries) {
    if (!entry || isGeneratedIntegrationTarget(entry.targetPath)) continue;

    if (isTemplateToolsPath(entry.targetPath, OPENCLAW_WORKSPACE_ROOT)) {
      hasWorkspaceTools = true;
      nextEntries.push({
        ...entry,
        contentBuffer: Buffer.from(
          upsertGeneratedIntegrationPromptBlock(entry.contentBuffer.toString("utf8")),
          "utf8",
        ),
      });
      continue;
    }

    if (isTemplateToolsPath(entry.targetPath, OPENCLAW_LEGACY_AGENT_TEMPLATE_ROOT)) {
      hasLegacyTools = true;
      nextEntries.push({
        ...entry,
        contentBuffer: Buffer.from(
          upsertGeneratedIntegrationPromptBlock(entry.contentBuffer.toString("utf8")),
          "utf8",
        ),
      });
      continue;
    }

    nextEntries.push(entry);
  }

  const defaultToolsContent = "## Tools\n\n";
  if (!hasWorkspaceTools) {
    nextEntries.push({
      targetPath: path.posix.join(OPENCLAW_WORKSPACE_ROOT, "TOOLS.md"),
      contentBuffer: Buffer.from(
        upsertGeneratedIntegrationPromptBlock(defaultToolsContent),
        "utf8",
      ),
      mode: 0o644,
    });
  }
  if (!hasLegacyTools) {
    nextEntries.push({
      targetPath: path.posix.join(OPENCLAW_LEGACY_AGENT_TEMPLATE_ROOT, "TOOLS.md"),
      contentBuffer: Buffer.from(
        upsertGeneratedIntegrationPromptBlock(defaultToolsContent),
        "utf8",
      ),
      mode: 0o644,
    });
  }

  const emptyManifest = buildSplitIntegrationManifest([]);
  nextEntries.push(
    {
      targetPath: NORA_SYNC_INTEGRATIONS_CATALOG_FILE,
      contentBuffer: Buffer.from(`${JSON.stringify(emptyManifest.catalog, null, 2)}\n`, "utf8"),
      mode: 0o644,
    },
    {
      targetPath: path.posix.join(OPENCLAW_WORKSPACE_ROOT, NORA_INTEGRATIONS_CONTEXT_FILE),
      contentBuffer: Buffer.from(buildEmptyIntegrationContextMarkdown(), "utf8"),
      mode: 0o644,
    },
    {
      targetPath: path.posix.join(OPENCLAW_WORKSPACE_ROOT, NORA_INTEGRATIONS_SKILL_FILE),
      contentBuffer: Buffer.from(`${buildIntegrationSkillMarkdown([])}\n`, "utf8"),
      mode: 0o644,
    },
  );

  return nextEntries;
}

function buildTemplatePayloadBootstrapFiles(templatePayload = {}) {
  return normalizeTemplatePayloadEntries(templatePayload).map((entry) => ({
    name: entry.targetPath.replace(/^\/+/, ""),
    content: entry.contentBuffer,
    mode: entry.mode,
  }));
}

const { shellSingleQuote } = require("./containerCommand");

function buildTemplatePayloadBootstrapCommand(templatePayload = {}) {
  const entries = normalizeTemplatePayloadEntries(templatePayload);
  if (entries.length === 0) return "";

  return entries
    .map(({ targetPath, contentBuffer, mode }) => {
      const quotedDir = shellSingleQuote(path.posix.dirname(targetPath));
      const quotedPath = shellSingleQuote(targetPath);
      return (
        `mkdir -p ${quotedDir} && ` +
        `printf '%s' '${contentBuffer.toString("base64")}' | base64 -d > ${quotedPath} && ` +
        `chmod ${mode.toString(8)} ${quotedPath} && `
      );
    })
    .join("");
}

// OpenClaw provider id used when registering Microsoft Foundry / Azure
// OpenAI in openclaw.json. Nora's internal provider id ("microsoft-foundry")
// is the UI/DB label; OpenClaw needs the id the integration guide uses
// (https://techcommunity.microsoft.com/blog/educatordeveloperblog/integrating-microsoft-foundry-with-openclaw-step-by-step-model-configuration/4495586),
// which is `azure-openai-responses`. Model strings handed to OpenClaw must
// be prefixed with this id, not "microsoft-foundry/".
const FOUNDRY_OPENCLAW_PROVIDER_ID = "azure-openai-responses";

// Common Foundry deployment ids surfaced in the Nora wizard. OpenClaw's
// custom-provider resolver will accept any deployment name via its catch-all
// path, but listing models here adds metadata (cost, context window, compat)
// that OpenClaw uses for cost tracking and correct request shape. The key
// compat flag is `supportsStore: false` — Azure rejects `store: true`, which
// is OpenClaw's default for Responses API.
const FOUNDRY_DEFAULT_MODELS = [
  {
    id: "gpt-5.5",
    name: "GPT-5.5 (Azure)",
    reasoning: true,
    contextWindow: 400000,
    maxTokens: 16384,
  },
  {
    id: "gpt-5.5-mini",
    name: "GPT-5.5 Mini (Azure)",
    reasoning: true,
    contextWindow: 400000,
    maxTokens: 16384,
  },
  {
    id: "gpt-5.5-pro",
    name: "GPT-5.5 Pro (Azure)",
    reasoning: true,
    contextWindow: 200000,
    maxTokens: 128000,
  },
  {
    id: "gpt-5.5",
    name: "GPT-5.5 (Azure)",
    reasoning: true,
    contextWindow: 200000,
    maxTokens: 128000,
  },
  {
    id: "gpt-5.2-codex",
    name: "GPT-5.2 Codex (Azure)",
    reasoning: true,
    contextWindow: 400000,
    maxTokens: 16384,
  },
  { id: "o3", name: "o3 (Azure)", reasoning: true, contextWindow: 200000, maxTokens: 100000 },
];

// Azure deployment names are arbitrary per resource (e.g. "gpt-5.5-1"), so the
// real deployment is supplied via MICROSOFT_FOUNDRY_DEPLOYMENT (sourced from the
// saved provider's model/config). Fall back to the canonical "gpt-5.5" when
// unset so existing single-deployment setups keep working.
const FOUNDRY_FALLBACK_DEPLOYMENT = "gpt-5.5";
const FOUNDRY_MODEL_PROVIDER_PREFIXES = Object.freeze([
  FOUNDRY_OPENCLAW_PROVIDER_ID,
  "microsoft-foundry",
  "openai",
  "openai-responses",
]);

function normalizeFoundryDeployment(value) {
  let deployment = String(value || "").trim();
  for (const providerId of FOUNDRY_MODEL_PROVIDER_PREFIXES) {
    const providerPrefix = `${providerId}/`;
    if (deployment.startsWith(providerPrefix)) {
      deployment = deployment.slice(providerPrefix.length).trim();
      break;
    }
  }
  return deployment && !deployment.includes("/") ? deployment : "";
}

function resolveFoundryDeployment(env = {}) {
  const configured = normalizeFoundryDeployment(
    env.MICROSOFT_FOUNDRY_DEPLOYMENT || env.NORA_DEFAULT_OPENCLAW_MODEL,
  );
  return configured || FOUNDRY_FALLBACK_DEPLOYMENT;
}

// The default model string OpenClaw should boot with for Foundry, e.g.
// "azure-openai-responses/gpt-5.5-1".
function foundryDefaultModel(env = {}) {
  return `${FOUNDRY_OPENCLAW_PROVIDER_ID}/${resolveFoundryDeployment(env)}`;
}

function buildFoundryModelEntries(env = {}) {
  // Ensure the actually-configured deployment is registered even if it isn't
  // one of the well-known ids below — otherwise OpenClaw throws "Unknown model"
  // for the very deployment we set as default.
  const deployment = resolveFoundryDeployment(env);
  const seen = new Set();
  const models = FOUNDRY_DEFAULT_MODELS.filter((entry) => {
    if (seen.has(entry.id)) return false;
    seen.add(entry.id);
    return true;
  }).map((entry) => ({
    id: entry.id,
    name: entry.name,
    api: "azure-openai-responses",
    reasoning: entry.reasoning,
    input: ["text", "image"],
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    contextWindow: entry.contextWindow,
    maxTokens: entry.maxTokens,
    compat: { supportsStore: false, supportsReasoningEffort: true },
  }));
  if (!deployment || models.some((model) => model.id === deployment)) return models;

  const baseModelId = deployment.replace(/-\d+$/, "");
  const template =
    models.find((model) => model.id === baseModelId) ||
    models.find((model) => model.id === "gpt-5.5") ||
    models[0];
  return [
    {
      ...template,
      id: deployment,
      name: `${deployment} (Azure deployment)`,
    },
    ...models,
  ];
}

// Builds the `models.providers.*` map injected into openclaw.json for
// providers OpenClaw doesn't ship in its native registry. Registering a
// provider here unlocks OpenClaw's custom-provider resolution path so
// `<provider>/<deployment>` model strings resolve instead of throwing
// "Unknown model" (the upstream check at openclaw's resolveModelWithRegistry).
//
// Microsoft Foundry: the underlying inference SDK (`@mariozechner/pi-ai`)
// ships a dedicated `azure-openai-responses` API
// (node_modules/@mariozechner/pi-ai/dist/providers/azure-openai-responses.js)
// that uses `new AzureOpenAI({apiKey, baseURL, apiVersion: "v1"})`. This is
// the right route — the SDK natively sends the `api-key` header that Azure
// requires, so we do NOT need the `authHeader: false` + manual
// `headers["api-key"]` workaround from the Microsoft community blog (which
// routes through the wrong API and forces a workaround).
//
// Required fields:
//   - provider id (key): `azure-openai-responses` — matches pi-ai's API name
//     AND OpenClaw's hardcoded OPENAI_RESPONSES_PROVIDERS allowlist
//   - `api: "azure-openai-responses"` — routes to streamAzureOpenAIResponses
//   - `baseUrl: <per-resource v1 URL, no trailing slash>` — pi-ai's
//     resolveAzureConfig consumes this via `model.baseUrl`
//   - `apiKey: <decrypted key>` — passed to the AzureOpenAI constructor
//   - `models[].compat.supportsStore: false` — Azure rejects `store: true`
//
// The baseUrl + key are required — without them the registration is omitted
// (caller hits the original "Unknown model" error, which correctly signals
// the user to configure the provider before retrying).
function buildOpenClawCustomProviders(env = {}) {
  const providers = {};
  const foundryKey = env.MICROSOFT_FOUNDRY_API_KEY;
  const foundryBaseUrlRaw = env.MICROSOFT_FOUNDRY_BASE_URL;
  if (foundryKey && foundryBaseUrlRaw) {
    // Strip trailing slash to match Azure's documented v1 URL shape
    // (https://<resource>.openai.azure.com/openai/v1 or
    // https://<resource>.cognitiveservices.azure.com/openai/v1).
    const foundryBaseUrl = String(foundryBaseUrlRaw).replace(/\/+$/, "");
    providers[FOUNDRY_OPENCLAW_PROVIDER_ID] = {
      api: "azure-openai-responses",
      baseUrl: foundryBaseUrl,
      apiKey: foundryKey,
      models: buildFoundryModelEntries(env),
    };
  }
  // Nora's zero-key demo provider: an OpenAI-compatible stub served by the
  // control plane itself. The worker injects the derived token plus the
  // in-network base URL (sister env var, same mechanism as Foundry's).
  const demoToken = env.NORA_DEMO_LLM_TOKEN;
  const demoBaseUrl = env.NORA_DEMO_LLM_BASE_URL;
  if (demoToken && demoBaseUrl) {
    providers[DEMO_OPENCLAW_PROVIDER_ID] = {
      api: "openai-completions",
      baseUrl: String(demoBaseUrl).replace(/\/+$/, ""),
      apiKey: demoToken,
      models: [
        {
          id: DEMO_OPENCLAW_MODEL_ID,
          name: "Nora Demo (deterministic stub)",
          api: "openai-completions",
          reasoning: false,
          input: ["text"],
          cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
          contextWindow: 32768,
          maxTokens: 4096,
        },
      ],
    };
  }
  return providers;
}

// OpenClaw-side ids for the zero-key demo provider. Distinct from Nora's
// internal "demo" id so a future builtin OpenClaw provider can't collide.
const DEMO_OPENCLAW_PROVIDER_ID = "nora-demo";
const DEMO_OPENCLAW_MODEL_ID = "nora-demo-1";

// Maps Nora's internal LLM provider id to the OpenClaw provider id that
// must appear in model strings (e.g. `<provider>/<deployment>`). Only Foundry
// and the demo stub need translation; everything else passes through unchanged.
const NORA_TO_OPENCLAW_PROVIDER_ID = Object.freeze({
  "microsoft-foundry": FOUNDRY_OPENCLAW_PROVIDER_ID,
  demo: DEMO_OPENCLAW_PROVIDER_ID,
});

function mapNoraProviderIdToOpenClaw(noraProviderId) {
  if (!noraProviderId) return noraProviderId;
  return NORA_TO_OPENCLAW_PROVIDER_ID[noraProviderId] || noraProviderId;
}

function buildOpenClawModelForProvider(noraProviderId, modelId) {
  const providerId = String(noraProviderId || "").trim();
  const rawModelId = String(modelId || "").trim();
  if (!providerId || !rawModelId) return null;

  if (providerId === "microsoft-foundry") {
    const deployment = normalizeFoundryDeployment(rawModelId);
    return deployment ? `${FOUNDRY_OPENCLAW_PROVIDER_ID}/${deployment}` : null;
  }

  const openclawProvider = mapNoraProviderIdToOpenClaw(providerId);
  return rawModelId.includes("/") ? rawModelId : `${openclawProvider}/${rawModelId}`;
}

const OPENCLAW_SQLITE_AUTH_SKIP_PROVIDERS = Object.freeze([
  "microsoft-foundry",
  FOUNDRY_OPENCLAW_PROVIDER_ID,
  "demo",
  DEMO_OPENCLAW_PROVIDER_ID,
]);

function buildOpenClawAuthImportFromFileCommand(options = {}) {
  const authPath = options.authPath || OPENCLAW_AUTH_PROFILES_PATH;
  const agentId = options.agentId || "main";
  const requireCli = options.requireCli === true;

  return [
    'OPENCLAW_BIN="${OPENCLAW_CLI_PATH:-/usr/local/bin/openclaw}"',
    'if [ ! -x "$OPENCLAW_BIN" ]; then OPENCLAW_BIN="$(command -v openclaw 2>/dev/null || true)"; fi',
    requireCli
      ? '[ -n "$OPENCLAW_BIN" ] && [ -x "$OPENCLAW_BIN" ] || exit 127'
      : 'if [ -n "$OPENCLAW_BIN" ] && [ -x "$OPENCLAW_BIN" ]; then',
    "export HOME=/root",
    "export OPENCLAW_BIN",
    "node <<'__NORA_OPENCLAW_AUTH_SQLITE_IMPORT__'",
    "const fs = require('fs');",
    "const { spawnSync } = require('child_process');",
    `const authPath = ${JSON.stringify(authPath)};`,
    `const agentId = ${JSON.stringify(agentId)};`,
    `const skipProviders = new Set(${JSON.stringify(OPENCLAW_SQLITE_AUTH_SKIP_PROVIDERS)});`,
    "let auth = {};",
    "try { auth = JSON.parse(fs.readFileSync(authPath, 'utf8')); } catch { process.exit(0); }",
    "const profiles = auth && auth.profiles && typeof auth.profiles === 'object' ? auth.profiles : {};",
    "for (const [profileId, profile] of Object.entries(profiles)) {",
    "  if (!profile || profile.type !== 'api_key' || !profile.key) continue;",
    "  const provider = String(profile.provider || '').trim();",
    "  if (!provider || skipProviders.has(provider)) continue;",
    "  const result = spawnSync(process.env.OPENCLAW_BIN, [",
    "    'models',",
    "    'auth',",
    "    '--agent',",
    "    agentId,",
    "    'paste-api-key',",
    "    '--provider',",
    "    provider,",
    "    '--profile-id',",
    "    String(profileId),",
    "  ], {",
    "    input: `${String(profile.key)}\\n`,",
    "    encoding: 'utf8',",
    "    stdio: ['pipe', 'pipe', 'pipe'],",
    "    env: process.env,",
    "  });",
    "  if (result.status !== 0) {",
    "    if (result.stderr) process.stderr.write(result.stderr);",
    "    if (result.stdout) process.stderr.write(result.stdout);",
    "    process.exit(result.status || 1);",
    "  }",
    "}",
    "__NORA_OPENCLAW_AUTH_SQLITE_IMPORT__",
    requireCli ? "" : "fi",
  ]
    .filter((line) => line !== "")
    .join("\n");
}

function buildOpenClawAuthProfilesWriteCommand(authProfiles, options = {}) {
  const authPath = options.authPath || OPENCLAW_AUTH_PROFILES_PATH;
  const authDir = authPath.slice(0, authPath.lastIndexOf("/")) || ".";
  const authJsonB64 = Buffer.from(
    JSON.stringify(authProfiles || { version: 1, profiles: {} }),
  ).toString("base64");

  return [
    "set -eu",
    `mkdir -p ${shellSingleQuote(authDir)}`,
    `printf '%s' '${authJsonB64}' | base64 -d > ${shellSingleQuote(authPath)}`,
    `chmod 0600 ${shellSingleQuote(authPath)}`,
    buildOpenClawAuthImportFromFileCommand({ ...options, authPath }),
  ].join("\n");
}

function buildOpenClawConfigMergeScript(gatewayConfig) {
  return [
    "cat <<'__NORA_MANAGED_OPENCLAW_CONFIG__' > /tmp/nora-managed-openclaw.json",
    JSON.stringify(gatewayConfig || {}, null, 2),
    "__NORA_MANAGED_OPENCLAW_CONFIG__",
    "node <<'__NORA_MERGE_OPENCLAW_CONFIG__'",
    "const fs = require('fs');",
    "const path = require('path');",
    "const configPath = '/root/.openclaw/openclaw.json';",
    "const managedPath = '/tmp/nora-managed-openclaw.json';",
    "function isPlainObject(value) {",
    "  return Boolean(value) && typeof value === 'object' && !Array.isArray(value);",
    "}",
    "function mergeConfig(current, managed) {",
    "  if (!isPlainObject(managed)) return managed;",
    "  const next = isPlainObject(current) ? { ...current } : {};",
    "  for (const [key, value] of Object.entries(managed)) {",
    "    next[key] = isPlainObject(value) ? mergeConfig(next[key], value) : value;",
    "  }",
    "  return next;",
    "}",
    "let current = {};",
    "try {",
    "  if (fs.existsSync(configPath)) {",
    "    current = JSON.parse(fs.readFileSync(configPath, 'utf8'));",
    "  }",
    "} catch {",
    "  current = {};",
    "}",
    "const managed = JSON.parse(fs.readFileSync(managedPath, 'utf8'));",
    "const next = mergeConfig(current, managed);",
    "fs.mkdirSync(path.dirname(configPath), { recursive: true });",
    "fs.writeFileSync(configPath, JSON.stringify(next, null, 2) + '\\n');",
    "fs.chmodSync(configPath, 0o600);",
    "__NORA_MERGE_OPENCLAW_CONFIG__",
    "rm -f /tmp/nora-managed-openclaw.json",
  ];
}

// Sync-time variant: returns a single shell command string suitable for
// runRuntimeCommand / docker exec that merges the given openclaw.json
// delta on a running container without restarting. Reuses the same
// merge semantics as the boot-time script so both paths agree.
function buildOpenClawConfigMergeCommand(configDelta) {
  return buildOpenClawConfigMergeScript(configDelta).join("\n");
}

// buildMcpServersConfig lives in its own dependency-free module so it can be
// unit-tested without loading the rest of the bootstrap; re-exported here for
// the worker/adapter consumers that already import from runtimeBootstrap.
const { buildMcpServersConfig } = require("./mcpServersConfig");

function buildRuntimeBootstrapCommand() {
  return [
    "mkdir -p /opt/openclaw-runtime/lib /var/log && ",
    ...RUNTIME_FILES.map(
      ({ relPath, sourceB64 }) =>
        `printf '%s' '${sourceB64}' | base64 -d > /opt/openclaw-runtime/lib/${relPath} && `,
    ),
    `printf '%s' '${INTEGRATION_TOOL_WRAPPER_B64}' | base64 -d > /usr/local/bin/${NORA_INTEGRATION_TOOL_COMMAND} && `,
    `chmod 755 /usr/local/bin/${NORA_INTEGRATION_TOOL_COMMAND} && `,
    "touch /var/log/openclaw-agent.log && ",
    'TSX_BIN="${OPENCLAW_TSX_BIN:-$(command -v tsx 2>/dev/null || true)}"; [ -n "$TSX_BIN" ] || TSX_BIN="tsx"; "$TSX_BIN" /opt/openclaw-runtime/lib/agent.ts >> /var/log/openclaw-agent.log 2>&1 & ',
  ].join("");
}

function buildOpenClawInstallCommand(packages = ["openclaw@latest"]) {
  const normalizedPackages = (Array.isArray(packages) ? packages : [packages])
    .map((pkg) => String(pkg || "").trim())
    .filter(Boolean);

  if (normalizedPackages.length === 0) {
    throw new Error("buildOpenClawInstallCommand requires at least one package");
  }

  const invalidPackage = normalizedPackages.find((pkg) => !/^[a-zA-Z0-9@._+/-]+$/.test(pkg));
  if (invalidPackage) {
    throw new Error(`Invalid package spec: ${invalidPackage}`);
  }

  const packageList = [...normalizedPackages, TSX_PACKAGE_SPEC].join(" ");

  return [
    'OPENCLAW_BIN="${OPENCLAW_CLI_PATH:-/usr/local/bin/openclaw}"; ',
    'OPENCLAW_TSX_BIN="${OPENCLAW_TSX_BIN:-/usr/local/bin/tsx}"; ',
    'DETECTED_OPENCLAW_BIN="$(command -v openclaw 2>/dev/null || true)"; ',
    'DETECTED_OPENCLAW_TSX_BIN="$(command -v tsx 2>/dev/null || true)"; ',
    'if [ -n "$DETECTED_OPENCLAW_BIN" ] && [ ! -x "$OPENCLAW_BIN" ]; then OPENCLAW_BIN="$DETECTED_OPENCLAW_BIN"; fi; ',
    'if [ -n "$DETECTED_OPENCLAW_TSX_BIN" ] && [ ! -x "$OPENCLAW_TSX_BIN" ]; then OPENCLAW_TSX_BIN="$DETECTED_OPENCLAW_TSX_BIN"; fi; ',
    'if ([ -n "$OPENCLAW_BIN" ] && [ -x "$OPENCLAW_BIN" ] && "$OPENCLAW_BIN" --version >/dev/null 2>&1) && ([ -n "$OPENCLAW_TSX_BIN" ] && [ -x "$OPENCLAW_TSX_BIN" ] && "$OPENCLAW_TSX_BIN" --version >/dev/null 2>&1); then ',
    "  true; ",
    "else ",
    '  rm -f "${OPENCLAW_CLI_PATH:-/usr/local/bin/openclaw}"; ',
    '  rm -f "${OPENCLAW_TSX_BIN:-/usr/local/bin/tsx}"; ',
    "  rm -rf /usr/local/lib/node_modules/openclaw; ",
    "  rm -rf /usr/local/lib/node_modules/tsx; ",
    "  npm uninstall -g openclaw tsx >/dev/null 2>&1 || true; ",
    "  (apt-get update -qq && apt-get install -y -qq git >/dev/null 2>&1 || true); ",
    `  if ! npm install -g ${packageList} >/tmp/openclaw-install.log 2>&1; then cat /tmp/openclaw-install.log >&2; exit 1; fi; `,
    "  hash -r 2>/dev/null || true; ",
    '  DETECTED_OPENCLAW_BIN="$(command -v openclaw 2>/dev/null || true)"; ',
    '  DETECTED_OPENCLAW_TSX_BIN="$(command -v tsx 2>/dev/null || true)"; ',
    '  if [ -n "${OPENCLAW_CLI_PATH:-}" ] && [ -n "$DETECTED_OPENCLAW_BIN" ] && [ "$DETECTED_OPENCLAW_BIN" != "$OPENCLAW_CLI_PATH" ]; then ',
    '    ln -sf "$DETECTED_OPENCLAW_BIN" "$OPENCLAW_CLI_PATH"; ',
    '    OPENCLAW_BIN="$OPENCLAW_CLI_PATH"; ',
    "  else ",
    '    OPENCLAW_BIN="${OPENCLAW_CLI_PATH:-$DETECTED_OPENCLAW_BIN}"; ',
    "  fi; ",
    '  if [ -n "${OPENCLAW_TSX_BIN:-}" ] && [ -n "$DETECTED_OPENCLAW_TSX_BIN" ] && [ "$DETECTED_OPENCLAW_TSX_BIN" != "$OPENCLAW_TSX_BIN" ]; then ',
    '    ln -sf "$DETECTED_OPENCLAW_TSX_BIN" "$OPENCLAW_TSX_BIN"; ',
    '    OPENCLAW_TSX_BIN="${OPENCLAW_TSX_BIN:-$DETECTED_OPENCLAW_TSX_BIN}"; ',
    "  else ",
    '    OPENCLAW_TSX_BIN="${OPENCLAW_TSX_BIN:-$DETECTED_OPENCLAW_TSX_BIN}"; ',
    "  fi; ",
    '  if ! ([ -n "$OPENCLAW_BIN" ] && [ -x "$OPENCLAW_BIN" ] && "$OPENCLAW_BIN" --version >/dev/null 2>&1); then cat /tmp/openclaw-install.log >&2; exit 1; fi; ',
    '  if ! ([ -n "$OPENCLAW_TSX_BIN" ] && [ -x "$OPENCLAW_TSX_BIN" ] && "$OPENCLAW_TSX_BIN" --version >/dev/null 2>&1); then cat /tmp/openclaw-install.log >&2; exit 1; fi; ',
    "fi; ",
    'export OPENCLAW_CLI_PATH="$OPENCLAW_BIN"; ',
    'export OPENCLAW_TSX_BIN="$OPENCLAW_TSX_BIN"; ',
    "true && ",
  ].join("");
}

function buildRuntimeEnv() {
  const env = {
    AGENT_HTTP_PORT: String(AGENT_RUNTIME_PORT),
    OPENCLAW_GATEWAY_PORT: String(OPENCLAW_GATEWAY_PORT),
    // Nora reaches managed gateways through recorded endpoints; mDNS is noisy
    // in container networks.
    OPENCLAW_DISABLE_BONJOUR: process.env.OPENCLAW_DISABLE_BONJOUR || "1",
    BACKEND_API_URL:
      process.env.AGENT_RUNTIME_BACKEND_API_URL ||
      process.env.BACKEND_API_URL ||
      "http://backend-api:4000",
  };
  // Only forward OPENCLAW_CLI_PATH / OPENCLAW_TSX_BIN if the worker process
  // has them explicitly set — do NOT inject a default. The agent base image
  // sets these via `ENV` (see agent-runtime/Dockerfile.{openclaw,nemoclaw}-agent)
  // and different images install the binaries in different prefixes (the
  // OpenShell sandbox uses `/usr/bin`, the Nora OpenClaw image uses
  // `/usr/local/bin`). Blindly defaulting to `/usr/local/bin/openclaw` makes
  // the bootstrap fast-path check miss on the NemoClaw sandbox and fall
  // into the install branch, which then fails under the sandbox's UID-998
  // Landlock restrictions.
  if (process.env.OPENCLAW_CLI_PATH) {
    env.OPENCLAW_CLI_PATH = process.env.OPENCLAW_CLI_PATH;
  }
  if (process.env.OPENCLAW_TSX_BIN) {
    env.OPENCLAW_TSX_BIN = process.env.OPENCLAW_TSX_BIN;
  }
  return env;
}

module.exports = {
  NORA_INTEGRATIONS_CONTEXT_FILE,
  NORA_INTEGRATIONS_PROMPT_BEGIN,
  NORA_INTEGRATIONS_PROMPT_END,
  OPENCLAW_LEGACY_AGENT_TEMPLATE_ROOT,
  OPENCLAW_WORKSPACE_ROOT,
  buildIntegrationPromptPointerMarkdown,
  buildOpenClawInstallCommand,
  buildRuntimeBootstrapCommand,
  buildRuntimeBootstrapFiles,
  buildIntegrationToolWrapperScript,
  buildOpenClawConfigMergeScript,
  buildOpenClawConfigMergeCommand,
  buildOpenClawAuthImportFromFileCommand,
  buildOpenClawAuthProfilesWriteCommand,
  buildMcpServersConfig,
  buildOpenClawCustomProviders,
  mapNoraProviderIdToOpenClaw,
  buildOpenClawModelForProvider,
  FOUNDRY_OPENCLAW_PROVIDER_ID,
  DEMO_OPENCLAW_PROVIDER_ID,
  DEMO_OPENCLAW_MODEL_ID,
  resolveFoundryDeployment,
  foundryDefaultModel,
  buildTemplatePayloadBootstrapCommand,
  buildTemplatePayloadBootstrapFiles,
  buildRuntimeEnv,
  stripGeneratedIntegrationPromptBlock,
  upsertGeneratedIntegrationPromptBlock,
};
