// @ts-nocheck
const {
  buildSplitIntegrationManifest,
  buildIntegrationSkillMarkdown,
} = require("../../../agent-runtime/lib/integrationTools");
const { shellSingleQuote } = require("../../../agent-runtime/lib/containerCommand");

const HERMES_INTEGRATIONS_DIR = "/opt/data/workspace/integrations";
const HERMES_INTEGRATIONS_CONFIG_FILE = `${HERMES_INTEGRATIONS_DIR}/integrations.json`;
const HERMES_INTEGRATIONS_LEGACY_CONFIG_FILE = "/opt/data/integrations.json";
const HERMES_INTEGRATIONS_LEGACY_CONFIG_JSON_FILE = "/opt/data/integrations.config.json";
const HERMES_INTEGRATIONS_WORKSPACE_CONFIG_FILE = "/opt/data/workspace/integrations.config.json";
const HERMES_INTEGRATIONS_CONTEXT_FILE = `${HERMES_INTEGRATIONS_DIR}/NORA_INTEGRATIONS.md`;
const HERMES_INTEGRATIONS_SKILL_FILE = "/opt/data/home/.hermes/skills/nora-integrations/SKILL.md";
const HERMES_INTEGRATION_TOOL_COMMAND = "/usr/local/bin/nora-integration-tool";

function writeBase64FileCommand(filePath, content, mode = "0644") {
  const encoded = Buffer.from(String(content || ""), "utf8").toString("base64");
  const quotedPath = shellSingleQuote(filePath);
  const quotedDir = shellSingleQuote(filePath.split("/").slice(0, -1).join("/") || "/");
  return [
    `mkdir -p ${quotedDir}`,
    `printf '%s' ${shellSingleQuote(encoded)} | base64 -d > ${quotedPath}`,
    `chmod ${mode} ${quotedPath}`,
  ].join(" && ");
}

function buildHermesIntegrationContextMarkdown(integrations = []) {
  return [
    "# Nora Integrations",
    "",
    "This file is generated by Nora from the active integrations connected to this Hermes agent.",
    `Machine-readable integration metadata is available in \`${HERMES_INTEGRATIONS_DIR}\`. Start with \`${HERMES_INTEGRATIONS_CONFIG_FILE}\`, then follow each \`detailsFile\` only when credential/tool details are needed.`,
    "Use the installed `nora-integrations` skill and `nora-integration-tool` command to inspect connected provider credentials and env vars.",
    "",
    buildIntegrationSkillMarkdown(integrations, { frontmatter: false }),
  ].join("\n");
}

/**
 * Generate the Hermes-side inspection tool that exposes only redacted integration config.
 *
 * @returns {string} Python command-line tool source.
 */
function buildHermesIntegrationToolScript() {
  return `#!/usr/bin/env python3
import json
import os
import re
import sys

CONFIG_CANDIDATES = [
    os.environ.get("NORA_INTEGRATIONS_CONFIG", ""),
    "${HERMES_INTEGRATIONS_CONFIG_FILE}",
    "${HERMES_INTEGRATIONS_WORKSPACE_CONFIG_FILE}",
    "${HERMES_INTEGRATIONS_LEGACY_CONFIG_JSON_FILE}",
    "${HERMES_INTEGRATIONS_LEGACY_CONFIG_FILE}",
]
DIR_CANDIDATES = [
    os.environ.get("NORA_INTEGRATIONS_DIR", ""),
    "${HERMES_INTEGRATIONS_DIR}",
]
SENSITIVE_KEY_RE = re.compile(r"(token|secret|password|api[_-]?key|private[_-]?key|service[_-]?account|credentials?)", re.I)

def normalize_tool_name(value, fallback="integration"):
    candidate = re.sub(r"[^A-Za-z0-9_-]+", "_", str(value or fallback).strip())
    candidate = candidate.strip("_")
    return candidate or fallback

def provider_id(integration):
    return str(integration.get("provider") or integration.get("catalog_id") or integration.get("id") or "integration").strip().lower()

def manifest_tool_name(integration):
    return normalize_tool_name("nora_%s_integration" % provider_id(integration), "nora_integration")

def load_integrations():
    for directory in DIR_CANDIDATES:
        if not directory:
            continue
        catalog_path = os.path.join(directory, "integrations.json")
        loaded = load_integrations_from_file(catalog_path)
        if loaded is not None:
            return loaded
    for path in CONFIG_CANDIDATES:
        if not path:
            continue
        loaded = load_integrations_from_file(path)
        if loaded is not None:
            return loaded
    return []

def load_integrations_from_file(path):
    try:
        with open(path, "r", encoding="utf-8") as handle:
            raw = json.load(handle)
    except Exception:
        return None
    if isinstance(raw, list):
        return raw
    if not isinstance(raw, dict) or not isinstance(raw.get("integrations"), list):
        return None
    base_dir = os.path.dirname(path)
    loaded = []
    saw_details_file = False
    for entry in raw["integrations"]:
        if not isinstance(entry, dict) or not entry.get("detailsFile"):
            continue
        saw_details_file = True
        details_path = entry["detailsFile"]
        if not os.path.isabs(details_path):
            details_path = os.path.join(base_dir, details_path)
        try:
            with open(details_path, "r", encoding="utf-8") as detail_handle:
                detail = json.load(detail_handle)
            if isinstance(detail, dict) and isinstance(detail.get("integration"), dict):
                loaded.append(detail["integration"])
            elif isinstance(detail, dict):
                loaded.append(detail)
        except Exception:
            continue
    if saw_details_file:
        return loaded
    return raw["integrations"]

def safe_config(integration):
    config = integration.get("config") if isinstance(integration.get("config"), dict) else {}
    redacted = integration.get("redactedConfig") if isinstance(integration.get("redactedConfig"), dict) else {}
    safe = {}
    for key in sorted(set(list(config.keys()) + list(redacted.keys()))):
        if redacted.get(key) == "[REDACTED]" or SENSITIVE_KEY_RE.search(str(key)):
            safe[key] = "[REDACTED]"
        elif key in redacted:
            safe[key] = redacted[key]
        else:
            safe[key] = config.get(key)
    return safe

def summarize(integration):
    declared = integration.get("toolSpecs") if isinstance(integration.get("toolSpecs"), list) else []
    tools = [{
        "name": manifest_tool_name(integration),
        "description": "Inspect this integration manifest and credential env vars.",
        "operation": "manifest.inspect",
        "executable": True,
        "executionState": "runtime_skill",
        "executor": "nora-integration-tool",
        "invokeCommand": "nora-integration-tool %s '{}'" % manifest_tool_name(integration),
        "noraGenerated": True,
    }]
    for spec in declared:
        if not isinstance(spec, dict):
            continue
        tools.append({
            "name": spec.get("name") or "tool",
            "description": spec.get("description") or "",
            "operation": spec.get("operation"),
            "executable": False,
            "executionState": "manifest_only",
            "executor": None,
            "invokeCommand": None,
            "inputSchema": spec.get("inputSchema") or spec.get("parameters"),
            "noraGenerated": False,
        })
    return {
        "id": integration.get("id"),
        "provider": integration.get("provider") or integration.get("catalog_id") or integration.get("id"),
        "name": integration.get("name") or integration.get("provider"),
        "category": integration.get("category") or "unknown",
        "authType": integration.get("authType"),
        "status": integration.get("status") or "active",
        "capabilities": integration.get("capabilities") if isinstance(integration.get("capabilities"), list) else [],
        "credentialEnv": integration.get("credentialEnv") if isinstance(integration.get("credentialEnv"), dict) else {},
        "config": safe_config(integration),
        "api": integration.get("api") if isinstance(integration.get("api"), dict) else {},
        "mcp": integration.get("mcp"),
        "usageHints": integration.get("usageHints") if isinstance(integration.get("usageHints"), list) else [],
        "tools": tools,
    }

def print_json(payload):
    print(json.dumps(payload, indent=2, sort_keys=True))

def main():
    integrations = load_integrations()
    if len(sys.argv) < 2 or sys.argv[1] in ("--help", "-h"):
        print("nora-integration-tool --list")
        print("nora-integration-tool <nora_provider_integration> '{}'")
        return 0
    if sys.argv[1] == "--list":
        tools = []
        for integration in integrations:
            summary = summarize(integration)
            for tool in summary["tools"]:
                tools.append({
                    "provider": summary["provider"],
                    "providerName": summary["name"],
                    "toolName": tool["name"],
                    "description": tool["description"],
                    "operation": tool["operation"],
                    "executable": tool["executable"],
                    "executionState": tool["executionState"],
                    "invokeCommand": tool["invokeCommand"],
                })
        print_json({"tools": tools})
        return 0
    tool_name = sys.argv[1]
    for integration in integrations:
        if tool_name == manifest_tool_name(integration):
            print_json({
                "ok": True,
                "toolName": tool_name,
                "provider": provider_id(integration),
                "operation": "manifest.inspect",
                "result": {"integration": summarize(integration)},
            })
            return 0
    sys.stderr.write('Nora integration tool "%s" is not executable in this Hermes runtime\\n' % tool_name)
    return 1

if __name__ == "__main__":
    raise SystemExit(main())
`;
}

/**
 * Build an idempotent shell install for split integration manifests, skill docs, and tooling.
 *
 * Secret-bearing detail files are written mode 0600 after legacy manifest locations are removed.
 *
 * @param {Object[]} [integrations=[]] - Decrypted runtime sync entries.
 * @returns {string} Shell command that projects integrations into a Hermes workspace.
 */
function buildHermesIntegrationInstallCommand(integrations = []) {
  const syncedIntegrations = Array.isArray(integrations) ? integrations : [];
  const manifest = buildSplitIntegrationManifest(syncedIntegrations);
  const catalogJson = `${JSON.stringify(manifest.catalog, null, 2)}\n`;
  const skillMarkdown = `${buildIntegrationSkillMarkdown(syncedIntegrations)}\n`;
  const contextMarkdown = `${buildHermesIntegrationContextMarkdown(syncedIntegrations)}\n`;
  const toolScript = buildHermesIntegrationToolScript();

  return [
    "set -eu",
    `rm -rf ${shellSingleQuote(HERMES_INTEGRATIONS_DIR)}`,
    `rm -f ${[
      HERMES_INTEGRATIONS_LEGACY_CONFIG_FILE,
      HERMES_INTEGRATIONS_LEGACY_CONFIG_JSON_FILE,
      HERMES_INTEGRATIONS_WORKSPACE_CONFIG_FILE,
      "/opt/data/workspace/NORA_INTEGRATIONS.md",
    ]
      .map((filePath) => shellSingleQuote(filePath))
      .join(" ")}`,
    writeBase64FileCommand(HERMES_INTEGRATIONS_CONFIG_FILE, catalogJson, "0644"),
    ...manifest.details.map(({ fileName, integration }) =>
      writeBase64FileCommand(
        `${HERMES_INTEGRATIONS_DIR}/${fileName}`,
        `${JSON.stringify(integration, null, 2)}\n`,
        "0600",
      ),
    ),
    writeBase64FileCommand(HERMES_INTEGRATIONS_CONTEXT_FILE, contextMarkdown, "0644"),
    writeBase64FileCommand(HERMES_INTEGRATIONS_SKILL_FILE, skillMarkdown, "0644"),
    writeBase64FileCommand(HERMES_INTEGRATION_TOOL_COMMAND, toolScript, "0755"),
    `if [ -f /opt/data/.env ] && grep -q '^NORA_INTEGRATIONS_CONFIG=' /opt/data/.env; then true; else printf '\\nNORA_INTEGRATIONS_CONFIG=${HERMES_INTEGRATIONS_CONFIG_FILE}\\n' >> /opt/data/.env; fi`,
    `if [ -f /opt/data/.env ] && grep -q '^NORA_INTEGRATIONS_DIR=' /opt/data/.env; then true; else printf '\\nNORA_INTEGRATIONS_DIR=${HERMES_INTEGRATIONS_DIR}\\n' >> /opt/data/.env; fi`,
    "chown -R hermes:hermes /opt/data/home/.hermes /opt/data/workspace /opt/data/.env 2>/dev/null || true",
  ].join("\n");
}

module.exports = {
  HERMES_INTEGRATIONS_DIR,
  HERMES_INTEGRATIONS_CONFIG_FILE,
  HERMES_INTEGRATIONS_CONTEXT_FILE,
  HERMES_INTEGRATIONS_SKILL_FILE,
  buildHermesIntegrationInstallCommand,
  buildHermesIntegrationToolScript,
};
